# This file is the main config file for Serverless

service: auth-server
frameworkVersion: "3"

# Provider section

#  Provider declaration:
# - name of the provider
# - runtime supported by provider
# - region, where the functions are hosted
# - <other_option>: <value> , e.g.: timeout- optional, in seconds, default is 6
# - environment: This is where the environment variables for the function are defined

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
# Function section

# Function declaration
# All the Lambda functions
functions:
  # Function to get the authorization code:
  # - If not authorized, users are redirected to the Google authorization screen, where they can sign in with their Google credentials, which authorizes their access to the app.
  # - Once authorized, users will be redirected to the app with a code parameter in the URI.
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
